url: https://clubreal.world
title: Club Real World
permalink: /blog/:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog/


subscribe_rss: /feed.xml


exclude: ["vendor", "LICENSE", "_posts/LICENSE"]

plugins: ["jekyll-redirect-from", "jekyll-paginate"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

paginate: 10
paginate_path: "/blog/:num/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: blog/categories

authors:
  Herbie:
    name: Herbie

  Cory:
    name: Cory

  Charlie:
    name: Charlie
    
  Rob:
    name: Rob
    
  Lauren:
    name: Lauren

  Rob:
    name: Rob

